### ISSUE TITLE
Mongo Server issue

### ISSUE THREAD

**Issue by GisellaBella** [den-wdi-2/project-2#25]
keeps crashing, and i have no idea what as i keep getting a mysterious "tick" error

**Comment by GisellaBella** [comment]
it's some sort of mongo issue. I have shut down all my "experimental" code and gone back to the code state whenI was at least able to start  the server. Now i cant even get that to happen:
I am actively researching the interewebs to fix this, but at this rate I will literally have nothign to show tomorrow. 
error message:
Express server is up and running on http://localhost:3000/

/Users/gisellawalter/wdi/project2/node_modules/mongodb/lib/server.js:258
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/gisellawalter/wdi/project2/node_modules/mongodb-core/lib/topologies/server.js:309:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/gisellawalter/wdi/project2/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/gisellawalter/wdi/project2/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Gisellas-MacBook-Pro:project2 gisellawalter$
